import { createFileRoute } from '@tanstack/react-router';
import { Client } from 'pg';

const db = new Client({
  connectionString: process.env.DATABASE_URL,
});

// Initialize database connection
let isConnected = false;
async function ensureConnection() {
  if (!isConnected) {
    await db.connect();
    isConnected = true;
  }
}

export const Route = createFileRoute('/api/projects')({
  server: {
    handlers: {
      POST: async ({ request }: any) => {
        try {
          await ensureConnection();

          const body = await request.json();
          const { name, org_id } = body;

          if (!name || !org_id) {
            return Response.json(
              { error: 'Missing required fields: name and org_id' },
              { status: 400 }
            );
          }

          // Generate API key and slug
          const apiKey = `pw_${Math.random().toString(36).substring(2, 15)}${Math.random().toString(36).substring(2, 15)}`;
          const slug = name.toLowerCase().replace(/\s+/g, '-');

          // Insert project into database (UUID generated by database)
          const result = await db.query(
            `INSERT INTO projects (name, slug, org_id, api_key) 
             VALUES ($1, $2, $3, $4)
             RETURNING id, name, slug, org_id, api_key`,
            [name, slug, org_id, apiKey]
          );

          const project = result.rows[0];

          return Response.json({
            data: {
              id: project.id,
              name: project.name,
              slug: project.slug,
              org_id: project.org_id,
              api_key: project.api_key,
            },
          });
        } catch (error) {
          console.error('Error creating project:', error);
          return Response.json(
            { error: error instanceof Error ? error.message : 'Unknown error' },
            { status: 500 }
          );
        }
      },
    },
  },
});
